name: oidc-poc
on:
  push:
    branches:
    - '*'

jobs:
  auth:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    environment: ''
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
